# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CV_hw1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(769, 321)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 151, 251))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 80, 131, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 140, 131, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 200, 131, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 20, 151, 251))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")

        self.medium_filter_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.medium_filter_btn.setGeometry(QtCore.QRect(20, 50, 101, 41))
        self.medium_filter_btn.setObjectName("medium_filter_btn")

        self.gaussian_blur_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.gaussian_blur_btn.setGeometry(QtCore.QRect(20, 110, 101, 41))
        self.gaussian_blur_btn.setObjectName("gaussian_blur_btn")

        self.bilateral_filter = QtWidgets.QPushButton(self.groupBox_2)
        self.bilateral_filter.setGeometry(QtCore.QRect(20, 170, 101, 41))
        self.bilateral_filter.setObjectName("bilateral_filter")

        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(560, 20, 181, 251))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")

        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(10, 40, 47, 12))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 47, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 47, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 47, 12))
        self.label_4.setObjectName("label_4")

        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit.setGeometry(QtCore.QRect(60, 30, 71, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 110, 71, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(60, 70, 71, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 150, 71, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.trans_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.trans_btn.setGeometry(QtCore.QRect(30, 200, 121, 31))
        self.trans_btn.setObjectName("trans_btn")

        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(140, 40, 47, 12))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(120, 120, 47, 12))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(120, 160, 47, 12))
        self.label_7.setObjectName("label_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(390, 20, 151, 251))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")

        self.gaussin_blur2_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.gaussin_blur2_btn.setGeometry(QtCore.QRect(30, 40, 91, 31))
        self.gaussin_blur2_btn.setObjectName("gaussin_blur2_btn")

        self.sobelx_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.sobelx_btn.setGeometry(QtCore.QRect(30, 90, 91, 31))
        self.sobelx_btn.setObjectName("sobelx_btn")

        self.sobely_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.sobely_btn.setGeometry(QtCore.QRect(30, 140, 91, 31))
        self.sobely_btn.setObjectName("sobely_btn")

        self.magnitude_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.magnitude_btn.setGeometry(QtCore.QRect(30, 190, 91, 31))
        self.magnitude_btn.setObjectName("magnitude_btn")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 769, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "1. Image Processing"))
        self.pushButton.setText(_translate("MainWindow", "1.1 Load Image"))
        self.pushButton_2.setText(_translate("MainWindow", "1.2 Color Seperation"))
        self.pushButton_3.setText(_translate("MainWindow", "1.3 Image Flipping"))
        self.pushButton_4.setText(_translate("MainWindow", "1.4 Blending"))
        self.groupBox_2.setTitle(_translate("MainWindow", "2. Image Smoothing"))
        self.medium_filter_btn.setText(_translate("MainWindow", "2.1 Median Filter"))
        self.gaussian_blur_btn.setText(_translate("MainWindow", "2.2 Gaussian Blur"))
        self.bilateral_filter.setText(_translate("MainWindow", "2.3 Bilateral filter"))
        self.groupBox_4.setTitle(_translate("MainWindow", "4. Transformation"))
        self.label.setText(_translate("MainWindow", "Rotation : "))
        self.label_2.setText(_translate("MainWindow", "Scaling : "))
        self.label_3.setText(_translate("MainWindow", "Tx : "))
        self.label_4.setText(_translate("MainWindow", "Ty : "))
        self.trans_btn.setText(_translate("MainWindow", "4. Transformation"))
        self.label_5.setText(_translate("MainWindow", "deg"))
        self.label_6.setText(_translate("MainWindow", "pixel"))
        self.label_7.setText(_translate("MainWindow", "pixel"))
        self.groupBox_3.setTitle(_translate("MainWindow", "3. Edge Detection"))
        self.gaussin_blur2_btn.setText(_translate("MainWindow", "3.1 Gaussian Blur"))
        self.sobelx_btn.setText(_translate("MainWindow", "3.2 Sobel X"))
        self.sobely_btn.setText(_translate("MainWindow", "3.3 Sobel Y"))
        self.magnitude_btn.setText(_translate("MainWindow", "3.4 Magnitude"))
